### ISSUE TITLE
Resources$NotFoundException

### ISSUE THREAD

**Issue by subvert** [Mobideck/appdeck#41]
I created an Android build to publish. I then installed the APK on my phone so I could test the
built app. When the app starts up, it crashes immediately. Any idea what I can do to solve the problem?
The file called "**ic_arrow_back_white_24dp.xml**" seems to be the issue. I dont use any file named as such so I presume it is used by AppDek when building the app? I checked the log to see what happens and I find the following exception in my logs when trying to run the app:

05-11 10:06:48.032 1926-1926/? E/AndroidRuntime: FATAL EXCEPTION: main
		Process: co.za.mydomain.myapp, PID: 1926
		java.lang.RuntimeException: Unable to start activity ComponentInfo{co.za.mydomain.myapp/com.mobideck.appdeck.Loader}: android.content.res.Resources$NotFoundException: File res/drawable/ic_arrow_back_white_24dp.xml from drawable resource ID #0x7f02009c
			at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2429)
			at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
			at android.app.ActivityThread.access$800(ActivityThread.java:166)
			at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
			at android.os.Handler.dispatchMessage(Handler.java:102)
			at android.os.Looper.loop(Looper.java:136)
			at android.app.ActivityThread.main(ActivityThread.java:5584)
			at java.lang.reflect.Method.invokeNative(Native Method)
			at java.lang.reflect.Method.invoke(Method.java:515)
			at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
			at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
			at dalvik.system.NativeStart.main(Native Method)
		 Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_arrow_back_white_24dp.xml from drawable resource ID #0x7f02009c
			at android.content.res.Resources.loadDrawable(Resources.java:3453)
			at android.content.res.Resources.getDrawable(Resources.java:1896)
			at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:323)
			at com.mobideck.appdeck.Loader.onCreate(Loader.java:419)
			at android.app.Activity.performCreate(Activity.java:5447)
			at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
			at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2393)
			at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493) 
			at android.app.ActivityThread.access$800(ActivityThread.java:166) 
			at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283) 
			at android.os.Handler.dispatchMessage(Handler.java:102) 
			at android.os.Looper.loop(Looper.java:136) 
			at android.app.ActivityThread.main(ActivityThread.java:5584) 
			at java.lang.reflect.Method.invokeNative(Native Method) 
			at java.lang.reflect.Method.invoke(Method.java:515) 
			at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268) 
			at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084) 
			at dalvik.system.NativeStart.main(Native Method) 
		 Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #2: invalid drawable tag vector
			at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:969)
			at android.graphics.drawable.Drawable.createFromXml(Drawable.java:913)
			at android.content.res.Resources.loadDrawable(Resources.java:3449)
			at android.content.res.Resources.getDrawable(Resources.java:1896) 
			at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:323) 
			at com.mobideck.appdeck.Loader.onCreate(Loader.java:419) 
			at android.app.Activity.performCreate(Activity.java:5447) 
			at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094) 
			at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2393) 
			at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493) 
			at android.app.ActivityThread.access$800(ActivityThread.java:166) 
			at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283) 
			at android.os.Handler.dispatchMessage(Handler.java:102) 
			at android.os.Looper.loop(Looper.java:136) 
			at android.app.ActivityThread.main(ActivityThread.java:5584) 
			at java.lang.reflect.Method.invokeNative(Native Method) 
			at java.lang.reflect.Method.invoke(Method.java:515) 
			at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268) 
			at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084) 
			at dalvik.system.NativeStart.main(Native Method)

**Comment by mdekermadec** [comment]
There is a problem in Google Android Support libs and vector that could lead to a crash on some devices.

As we only use vector on only one image: ic_arrow_back_white_24dp.xml, I disable this features to solve the problem.

Could you check on your side if app still crash ?

Don't forget to ask for a new build before testing.

**Comment by subvert** [comment]
I asked for a new build and reinstalled it on my Android phone and it still crashed. Its giving the same exception as previously, except I noticed that there is a slight change in the stack trace. I see that it crashes now on **ResourcesCompat.getDrawable(ResourcesCompat.java:62)** where previously it crashed on  **android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:323)**.
So I am certain that I am using the new build. I pasted the new stack trace below:

05-11 23:02:58.988 13823-13823/? E/AndroidRuntime: FATAL EXCEPTION: main
	 Process: co.za.financiallyfree.ffreeapp, PID: 13823
	 java.lang.RuntimeException: Unable to start activity ComponentInfo{co.za.financiallyfree.ffreeapp/com.mobideck.appdeck.Loader}: android.content.res.Resources$NotFoundException: File res/drawable/ic_arrow_back_white_24dp.xml from drawable resource ID #0x7f02009c
		 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2429)
		 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
		 at android.app.ActivityThread.access$800(ActivityThread.java:166)
		 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
		 at android.os.Handler.dispatchMessage(Handler.java:102)
		 at android.os.Looper.loop(Looper.java:136)
		 at android.app.ActivityThread.main(ActivityThread.java:5584)
		 at java.lang.reflect.Method.invokeNative(Native Method)
		 at java.lang.reflect.Method.invoke(Method.java:515)
		 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
		 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
		 at dalvik.system.NativeStart.main(Native Method)
	  Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_arrow_back_white_24dp.xml from drawable resource ID #0x7f02009c
		 at android.content.res.Resources.loadDrawable(Resources.java:3453)
		 at android.content.res.Resources.getDrawable(Resources.java:1896)
		 at android.support.v4.content.res.ResourcesCompat.getDrawable(ResourcesCompat.java:62)
		 at com.mobideck.appdeck.Loader.onCreate(Loader.java:421)
		 at android.app.Activity.performCreate(Activity.java:5447)
		 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
		 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2393)
		 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493) 
		 at android.app.ActivityThread.access$800(ActivityThread.java:166) 
		 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283) 
		 at android.os.Handler.dispatchMessage(Handler.java:102) 
		 at android.os.Looper.loop(Looper.java:136) 
		 at android.app.ActivityThread.main(ActivityThread.java:5584) 
		 at java.lang.reflect.Method.invokeNative(Native Method) 
		 at java.lang.reflect.Method.invoke(Method.java:515) 
		 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268) 
		 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084) 
		 at dalvik.system.NativeStart.main(Native Method) 
	  Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #2: invalid drawable tag vector
		 at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:969)
		 at android.graphics.drawable.Drawable.createFromXml(Drawable.java:913)
		 at android.content.res.Resources.loadDrawable(Resources.java:3449)
		 at android.content.res.Resources.getDrawable(Resources.java:1896) 
		 at android.support.v4.content.res.ResourcesCompat.getDrawable(ResourcesCompat.java:62) 
		 at com.mobideck.appdeck.Loader.onCreate(Loader.java:421) 
		 at android.app.Activity.performCreate(Activity.java:5447) 
		 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094) 
		 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2393) 
		 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493) 
		 at android.app.ActivityThread.access$800(ActivityThread.java:166) 
		 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283) 
		 at android.os.Handler.dispatchMessage(Handler.java:102) 
		 at android.os.Looper.loop(Looper.java:136) 
		 at android.app.ActivityThread.main(ActivityThread.java:5584) 
		 at java.lang.reflect.Method.invokeNative(Native Method) 
		 at java.lang.reflect.Method.invoke(Method.java:515) 
		 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268) 
		 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084) 
		 at dalvik.system.NativeStart.main(Native Method)
