### ISSUE TITLE
Resources$NotFoundException

### ISSUE THREAD

**Issue by subvert** [Mobideck/appdeck#42]
Referring to #41. I asked for a new build and reinstalled it on my Android phone and it still crashed. Its giving the same exception as previously, except I noticed that there is a slight change in the stack trace. I see that it crashes now on **android.support.v4.content.res.ResourcesCompat.getDrawable(ResourcesCompat.java:62)** where previously it crashed on  **android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:323)**.
So I am certain that I am using the new build. I pasted the new stack trace below:

05-11 23:02:58.988 13823-13823/? E/AndroidRuntime: FATAL EXCEPTION: main
	 Process: co.za.financiallyfree.ffreeapp, PID: 13823
	 java.lang.RuntimeException: Unable to start activity ComponentInfo{co.za.financiallyfree.ffreeapp/com.mobideck.appdeck.Loader}: android.content.res.Resources$NotFoundException: File res/drawable/ic_arrow_back_white_24dp.xml from drawable resource ID #0x7f02009c
		 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2429)
		 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
		 at android.app.ActivityThread.access$800(ActivityThread.java:166)
		 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
		 at android.os.Handler.dispatchMessage(Handler.java:102)
		 at android.os.Looper.loop(Looper.java:136)
		 at android.app.ActivityThread.main(ActivityThread.java:5584)
		 at java.lang.reflect.Method.invokeNative(Native Method)
		 at java.lang.reflect.Method.invoke(Method.java:515)
		 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
		 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
		 at dalvik.system.NativeStart.main(Native Method)
	  Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_arrow_back_white_24dp.xml from drawable resource ID #0x7f02009c
		 at android.content.res.Resources.loadDrawable(Resources.java:3453)
		 at android.content.res.Resources.getDrawable(Resources.java:1896)
		 at android.support.v4.content.res.ResourcesCompat.getDrawable(ResourcesCompat.java:62)
		 at com.mobideck.appdeck.Loader.onCreate(Loader.java:421)
		 at android.app.Activity.performCreate(Activity.java:5447)
		 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
		 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2393)
		 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493) 
		 at android.app.ActivityThread.access$800(ActivityThread.java:166) 
		 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283) 
		 at android.os.Handler.dispatchMessage(Handler.java:102) 
		 at android.os.Looper.loop(Looper.java:136) 
		 at android.app.ActivityThread.main(ActivityThread.java:5584) 
		 at java.lang.reflect.Method.invokeNative(Native Method) 
		 at java.lang.reflect.Method.invoke(Method.java:515) 
		 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268) 
		 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084) 
		 at dalvik.system.NativeStart.main(Native Method) 
	  Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #2: invalid drawable tag vector
		 at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:969)
		 at android.graphics.drawable.Drawable.createFromXml(Drawable.java:913)
		 at android.content.res.Resources.loadDrawable(Resources.java:3449)
		 at android.content.res.Resources.getDrawable(Resources.java:1896) 
		 at android.support.v4.content.res.ResourcesCompat.getDrawable(ResourcesCompat.java:62) 
		 at com.mobideck.appdeck.Loader.onCreate(Loader.java:421) 
		 at android.app.Activity.performCreate(Activity.java:5447) 
		 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094) 
		 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2393) 
		 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493) 
		 at android.app.ActivityThread.access$800(ActivityThread.java:166) 
		 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283) 
		 at android.os.Handler.dispatchMessage(Handler.java:102) 
		 at android.os.Looper.loop(Looper.java:136) 
		 at android.app.ActivityThread.main(ActivityThread.java:5584) 
		 at java.lang.reflect.Method.invokeNative(Native Method) 
		 at java.lang.reflect.Method.invoke(Method.java:515) 
		 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268) 
		 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084) 
		 at dalvik.system.NativeStart.main(Native Method)

**Comment by mdekermadec** [comment]
Google seems to have a lot of problems with vector ... to stop this issue I replace vector xml by a pnp image.
I test on Android 4.1, 5.0 and 6.0 and no get crash at startup.

Could you validate on your side ?

If you still have a crash, can you tell me your Android version ?
